// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A conversion optimizer AI agent.
 *
 * - conversionOptimizer - A function that handles the conversion optimization process.
 * - ConversionOptimizerInput - The input type for the conversionOptimizer function.
 * - ConversionOptimizerOutput - The return type for the conversionOptimizer function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ConversionOptimizerInputSchema = z.object({
  landingPageData: z
    .string()
    .describe(
      'Data of the landing page that the conversion optimizer will analyze.'
    ),
  visitorInteractionData: z
    .string()
    .describe(
      'Data representing how visitors interact with the landing page.'
    ),
});

export type ConversionOptimizerInput = z.infer<typeof ConversionOptimizerInputSchema>;

const ConversionOptimizerOutputSchema = z.object({
  suggestions: z
    .string()
    .describe(
      'Suggestions to improve the landing page based on the analysis of the visitor interactions.'
    ),
});

export type ConversionOptimizerOutput = z.infer<typeof ConversionOptimizerOutputSchema>;

export async function conversionOptimizer(input: ConversionOptimizerInput): Promise<ConversionOptimizerOutput> {
  return conversionOptimizerFlow(input);
}

const prompt = ai.definePrompt({
  name: 'conversionOptimizerPrompt',
  input: {schema: ConversionOptimizerInputSchema},
  output: {schema: ConversionOptimizerOutputSchema},
  prompt: `You are a conversion optimization expert.

You will analyze the landing page data and visitor interaction data to provide suggestions to improve the landing page.

Landing Page Data: {{{landingPageData}}}
Visitor Interaction Data: {{{visitorInteractionData}}}

Suggestions:`,
});

const conversionOptimizerFlow = ai.defineFlow(
  {
    name: 'conversionOptimizerFlow',
    inputSchema: ConversionOptimizerInputSchema,
    outputSchema: ConversionOptimizerOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
